name: pusher_beams_server
description: A Pusher Beams Client for sending push notifications to users.
version: 0.1.0
homepage: https://pusher.com/beams
author: Suragch <studymongolian@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  jaguar_jwt: ^2.1.6

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
